### ISSUE TITLE
65-gce-disk-naming.rules throws error

### ISSUE THREAD

**Issue by rbalint** [GoogleCloudPlatform/guest-configs#14]
```
systemd-udevd[190]: /usr/lib/udev/rules.d/65-gce-disk-naming.rules:24 Invalid value "/bin/sh -c 'echo $((%n-1))'" for PROGRAM (char 18: invalid substitution type), ignoring, but please fix it.
```

**Comment by rbalint** [comment]
On Ubuntu 20.04

**Comment by hopkiw** [comment]
the 20.04 image in GCE does not yet have this updated version of the script, so do you mean you're testing it on 20.04?

this is a good catch. i'm unsure what impact it is having but i don't think it is limited to ubuntu. it seems udev rules support both % and $ syntax substitutions, so the use of a shell here for arithmetic was incorrect.

**Comment by rbalint** [comment]
I'm in the process of updating the Ubuntu packages.
