### ISSUE TITLE
Include package in Unattended Upgrades

### ISSUE THREAD

**Issue by ramshazar** [GoogleCloudPlatform/guest-configs#24]
Hi folks,

as stated in the [docs](https://cloud.google.com/compute/docs/images/os-details#auto-update-debian) this package is not updated via unattended upgrades.

An extract from /var/log/unattended-upgrades/unattended-upgrades.log shows as expected:
> 2021-07-05 08:45:37,699 DEBUG Checking: google-compute-engine ([<Origin component:'main' archive:'google-compute-engine-buster-stable' origin:'google-compute-engine-buster-stable' label:'google-compute-engine-buster-stable' site:'packages.cloud.google.com' isTrusted:True>])
2021-07-05 08:45:37,777 DEBUG pkg google-compute-engine not in allowed origin
2021-07-05 08:45:37,777 DEBUG sanity check failed

Is there a technical reason why the package should not be included?
If not I would prefer it if the official gce debian packages would be included. What do you think?

**Comment by hopkiw** [comment]
We don't own this file or configuration, @ramshazar. The debian image is configured by default only to perform security updates. Users can choose to make whatever rules they'd like, the responsibility is with them.
