### ISSUE TITLE
rsyslog.d/90-google.conf directs logging to /dev/console, but rsyslog doesn't have perm to open

### ISSUE THREAD

**Issue by suckatrash** [GoogleCloudPlatform/guest-configs#48]
This was originally reported here: https://github.com/GoogleCloudPlatform/compute-image-packages/issues/889
...and looks like still happening in Ubuntu 22.04.2 LTS as recently as the `ubuntu-2204-jammy-v20230302` builds.

**Comment by vorakl** [comment]
Thank you, @suckatrash  for bringing up this issue and providing with the background.
Unfortunately, there is nothing really we can help with.
The problem isn't related to this package or  Google Guest Environment software. We do not add rsyslog service  or configuring its integration with the distributions. We're just directing certain log messages to the console. It is up to the distributions how to configure supplied services.

For instance, you won't find this issue in other distributions. Here are a couple examples:

1. Debian

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ ls -l /dev/console 
crw------- 1 root root 5, 1 Apr 28 18:56 /dev/console

$ ps uax | grep rsyslog
root         364  0.0  0.0 220936  6304 ?        Ssl  Apr01   0:16 /usr/sbin/rsyslogd -n -iNONE
```

2. Rocky Linux

```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"

$ ls -l /dev/console 
crw--w----. 1 root tty 5, 1 Apr 28 18:58 /dev/console

$ ps uax | grep rsyslog
root         645  0.0  0.2 286832 16604 ?        Ssl  Apr19   0:41 /usr/sbin/rsyslogd -n
```

But, it does exist on Ubuntu.  Canonical builds all packages for the distribution. And, as it was mentions in the comment,
https://github.com/GoogleCloudPlatform/compute-image-packages/issues/889#issuecomment-1499726903,  there is implemented some trick with udev rules:

```
$ cat /usr/lib/udev/rules.d/99-gce.rules
# Give syslog write access to the kernel logs
KERNEL=="console", GROUP="syslog", MODE="0620"

# Switch to using NOOP as the default scheduler per GCE request
SUBSYSTEM=="block", ENV{DEVTYPE}!="partition", ACTION=="add|change", ENV{ID_VENDOR}=="*Google*", ATTR{queue/scheduler}="noop"
```

You won't find this file in the current repository. Apparently, there are some issues with this rule and how it fits teh overall configuration, but I'd suggest to file a bug with Canonical, similar to this one https://bugs.launchpad.net/ubuntu/+source/rsyslog/+bug/1890177

There is nothing we can do here. I'm closing the issue.

**Comment by wu0407** [comment]
same In Ubuntu 24.04 https://bugs.launchpad.net/ubuntu/+source/rsyslog/+bug/2065060

**Comment by wu0407** [comment]
I delete this instance, Ubuntu 24.04 minimal update, maybe on 5.2x

**Comment by yosida95** [comment]
@vorakl @ChaitanyaKulkarni28 sharing some additional findings in case they're useful.

I can confirm this issue still exists on both Ubuntu 22.04 and 24.04 GCE images:

- `projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20260702`
- `projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2404-noble-amd64-v20260630`

This looks related to #123, which reports the same issue on Ubuntu 24.04.

This issue can be triggered on demand by `sudo kill -HUP $(pgrep rsyslogd)`, letting rsyslog reopen its output files.

Adding the `syslog` user to the `tty` group resolves the issue, as mentioned in this thread and in the upstream bug [LP #2065060](https://bugs.launchpad.net/ubuntu/+source/rsyslog/+bug/2065060) and [LP #1890177](https://bugs.launchpad.net/ubuntu/+source/rsyslog/+bug/1890177).

Worth noting: none of the rules under `/etc/rsyslog.d/` route messages to `/dev/console` except `90-google.conf`. So the `google-compute-engine` package is the only thing on these images that actually triggers this bug.

The following investigation is on Ubuntu 24.04, but the result on Ubuntu 22.04 is technically the same except for the GID.

```console
ubuntu@ubuntu-2404:~$ ls -l /dev/console
crw--w---- 1 root tty 5, 1 Jul  6 11:21 /dev/console

ubuntu@ubuntu-2404:~$ cat /proc/$(pgrep rsyslogd)/status | grep -E "^Uid|^Gid"
Uid:    104     104     104     104
Gid:    106     106     106     106

ubuntu@ubuntu-2404:~$ getent group | grep -E '(^|:)(tty|106)'
tty:x:5:
syslog:x:106:

ubuntu@ubuntu-2404:~$ sudo grep /dev/console -r /etc/rsyslog.d/
/etc/rsyslog.d/90-google.conf:daemon,kern.* /dev/console

ubuntu@ubuntu-2404:~$ cat /etc/rsyslog.d/90-google.conf
# Google Compute Engine default console logging.
#
# daemon: logging from Google provided daemons.
# kern: logging information in case of an unexpected crash during boot.
#
daemon,kern.* /dev/console

```
